Step 2: intermediate
talanova/js-weather-forecast-repo pull request #3
Opened 2020-12-13 14:37 UTC by talanova

do more actions to config webpack and babel

2021-01-08 20:18 UTC, AntiHero requested changes

2021-01-08 20:18 UTC, AntiHero commented on src/constants.js
> +export const testWeather = {
как мы такие константы называем? CAMEL_CASE

2021-01-08 20:25 UTC, AntiHero requested changes

2021-01-08 20:25 UTC, AntiHero commented on .github/workflows/sanity-check.yml
> +      - name: Lint check
Test check)

2021-01-08 20:25 UTC, AntiHero commented on src/initial.test.js
> +  beforeEach(() => {
можно выносить beforeEach наверх, используй принцип DRY

2021-01-08 20:25 UTC, AntiHero commented on src/list.js
> +    e.preventDefault();
а нужен ли тут preventDefault?

2021-01-08 20:25 UTC, AntiHero commented on src/list.test.js
> +    // values stored in tests will also be available in other tests unless you run
не забывай пожалуйста удалять такие комменты

2021-01-08 20:33 UTC, AntiHero requested changes

2021-01-08 20:33 UTC, AntiHero commented on src/list.test.js
> +    return city === "moscow" ? mockWeather : null;
всё же тут мы возвращаем Promise.resolve(mockWeather/null), аналогично тому что функция getWeather возвращает Promise.resolve, согласна?

2021-01-09 13:59 UTC, talanova commented on src/constants.js
> +export const testWeather = {
переименовала

2021-01-09 13:59 UTC, talanova commented on src/constants.js
> +export const testWeather = {
переименовала

2021-01-09 13:59 UTC, talanova commented on .github/workflows/sanity-check.yml
> +      - name: Lint check
переименовала

2021-01-09 14:00 UTC, talanova commented on src/initial.test.js
> +  beforeEach(() => {
согласна, нужно было на уровень выше и не дублировать. исправила

2021-01-09 14:02 UTC, talanova commented on src/list.js
> +    e.preventDefault();
нет, убрала. был нужен в submit

2021-01-09 14:02 UTC, talanova commented on src/list.js
> +    e.preventDefault();
нет, убрала. был нужен в был в submit

2021-01-09 14:04 UTC, talanova commented on src/list.test.js
> +    // values stored in tests will also be available in other tests unless you run
убрала

2021-01-09 14:07 UTC, talanova commented on src/list.test.js
> +    return city === "moscow" ? mockWeather : null;
согласна, нужно было Promise.resolve возвращать. исправила

2021-01-09 19:35 UTC, AntiHero approved these changes

2021-01-10 15:50 UTC, merged